[package]
name = "rocket-voter"
version = "0.1.0"
authors = ["dmytro.pakhmanov <dmytro.pakhmanov@numberfour.eu>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rusqlite = {version = "0.16", features = ["chrono"]}
chrono = "0.4"
itertools = "0.8.0"